version: '2'
services:
   afthem:
      image: apifortress/bloodhound:latest
      container_name: bloodhound
      networks:
      - default
      volumes:
      - ./etc:/opt/afthem/etc
      - ./docker_log:/opt/afthem/log
      ports:
      - 8080:8080/tcp
      environment:
      - memorySettings=-Xms1024m -Xmx1024m